### ISSUE TITLE
when set Output file option runner fail

### ISSUE THREAD

**Issue by niwciu** [Uno-Takashi/Lizard-Runner#2]
It's not possible to generate output.html file.

When setting a step in job to that run lizard with options like bellow

```
      - name: Run Lizzard PushButton
        uses: niwciu/Lizard-Runner@v3
        with:
          path: "./src"
          CCN: "12"
          Threshold: "nloc=30"
          language: "cpp"
          verbose: "true"
          arguments: "4"
```
everything works fine (besides one warning) . 
![obraz](https://github.com/user-attachments/assets/22018388-32c0-459f-81dd-2686a85994f0)

After adding to the setup above output file generation option (shown below) it fail. 

```
      - name: Run Lizzard PushButton
        uses: niwciu/Lizard-Runner@v3
        with:
          path: "./src"
          CCN: "12"
          Threshold: "nloc=30"
          language: "cpp"
          verbose: "true"
          arguments: "4"
          output_file: "Lizard_report.html"
```

Bellow you can fin console output:

![obraz](https://github.com/user-attachments/assets/331631ee-eb11-4748-9b91-212ceab17560)
